"""Shared MCP tool filter parameters for gget.virus / fetch_virus_metadata."""

from typing import Any


def collect_filters(**kwargs: Any) -> dict[str, Any]:
    """Drop None values; keep explicit False booleans (e.g. annotated=False)."""
    return {key: value for key, value in kwargs.items() if value is not None}


def metadata_filter_kwargs(
    *,
    host: str | None = None,
    geographic_location: str | None = None,
    annotated: bool | None = None,
    complete_only: bool | None = None,
    refseq_only: bool | None = None,
    min_release_date: str | None = None,
) -> dict[str, Any]:
    return collect_filters(
        host=host,
        geographic_location=geographic_location,
        annotated=annotated,
        complete_only=complete_only,
        refseq_only=refseq_only,
        min_release_date=min_release_date,
    )


def virus_filter_kwargs(
    *,
    host: str | None = None,
    geographic_location: str | None = None,
    annotated: bool | None = None,
    complete_only: bool | None = None,
    refseq_only: bool | None = None,
    min_release_date: str | None = None,
    max_release_date: str | None = None,
    min_collection_date: str | None = None,
    max_collection_date: str | None = None,
    min_seq_length: int | None = None,
    max_seq_length: int | None = None,
    min_gene_count: int | None = None,
    max_gene_count: int | None = None,
    nuc_completeness: str | None = None,
    has_proteins: str | list[str] | None = None,
    proteins_complete: bool | None = None,
    lab_passaged: bool | None = None,
    submitter_country: str | None = None,
    min_mature_peptide_count: int | None = None,
    max_mature_peptide_count: int | None = None,
    min_protein_count: int | None = None,
    max_protein_count: int | None = None,
    max_ambiguous_chars: int | None = None,
    segment: str | list[str] | None = None,
    vaccine_strain: bool | None = None,
    source_database: str | None = None,
    lineage: str | list[str] | None = None,
    isolate: str | None = None,
    genotype: str | list[str] | None = None,
    isolation_source: str | None = None,
    env_source: str | list[str] | None = None,
    submitter_name: str | None = None,
    submitter_institution: str | None = None,
    gen_mol_type: str | None = None,
    genbank_metadata: bool | None = None,
    provirus: bool | None = None,
    is_sars_cov2: bool | None = None,
    is_alphainfluenza: bool | None = None,
    download_all_accessions: bool | None = None,
    genbank_batch_size: int | None = None,
    keep_temp: bool | None = None,
    verbose: bool | None = None,
    outfolder: str | None = None,
) -> dict[str, Any]:
    """All gget.virus parameters supported by retrieve_virus_dataset."""
    return collect_filters(
        host=host,
        geographic_location=geographic_location,
        annotated=annotated,
        complete_only=complete_only,
        refseq_only=refseq_only,
        min_release_date=min_release_date,
        max_release_date=max_release_date,
        min_collection_date=min_collection_date,
        max_collection_date=max_collection_date,
        min_seq_length=min_seq_length,
        max_seq_length=max_seq_length,
        min_gene_count=min_gene_count,
        max_gene_count=max_gene_count,
        nuc_completeness=nuc_completeness,
        has_proteins=has_proteins,
        proteins_complete=proteins_complete,
        lab_passaged=lab_passaged,
        submitter_country=submitter_country,
        min_mature_peptide_count=min_mature_peptide_count,
        max_mature_peptide_count=max_mature_peptide_count,
        min_protein_count=min_protein_count,
        max_protein_count=max_protein_count,
        max_ambiguous_chars=max_ambiguous_chars,
        segment=segment,
        vaccine_strain=vaccine_strain,
        source_database=source_database,
        lineage=lineage,
        isolate=isolate,
        genotype=genotype,
        isolation_source=isolation_source,
        env_source=env_source,
        submitter_name=submitter_name,
        submitter_institution=submitter_institution,
        gen_mol_type=gen_mol_type,
        genbank_metadata=genbank_metadata,
        provirus=provirus,
        is_sars_cov2=is_sars_cov2,
        is_alphainfluenza=is_alphainfluenza,
        download_all_accessions=download_all_accessions,
        genbank_batch_size=genbank_batch_size,
        keep_temp=keep_temp,
        verbose=verbose,
        outfolder=outfolder,
    )
